---
# tasks file for mariadb-container-role

- name: Add mariabd repo
  yum_repository:
    name: MariaDB
    description: Repo for installing MariaDB packages 
    baseurl: "http://yum.mariadb.org/{{ mariadb_version }}/centos7-amd64"
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: 1
    http_caching: none
    keepcache: 0 

- name: Install epel-release 
  yum:
    name: epel-release
    state: latest

- name: Install yum packages
  yum:
    name: "{{ item }}"
    state: latest 
  with_items:
    - mariadb-server
    - pwgen
    - ansible
    - nss_wrapper

- name: Purge yum cache
  command: yum clean all
  when: mariadb_clean_yum_cache

- name: Remove any unnecessary files 
  file:
    path: "{{ item }}" 
    state: absent
  with_items:
    - /usr/bin/mysql_embedded
    - /var/cache/yum

- name: Install dumb init
  get_url:
    url: https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64
    dest: /usr/bin/dumb-init
    owner: root
    group: root
    mode: 0775

- name: For mysql user add root group and change uid 
  user:
    name: mysql
    group: root
    groups: root
    append: yes
    uid: 1000

- name: Template entrypoint script
  template:
   src: entrypoint.sh.j2
   dest: /usr/bin/entrypoint.sh
   owner: mysql
   group: root
   mode: 0775

- name: Template my.cnf.j2
  template:
   src: my.cnf.j2
   dest: /etc/my.cnf
   owner: root 
   group: root
   mode: 0664

- name: Remove mariadb_datadir
  file: 
    path: /var/lib/mysql 
    state: absent   

- name: Set permissions on /var/log/mysql
  file:
    path: /var/log/mysql
    recurse: yes
    state: directory
    owner: mysql
    group: root
    mode: 0777   

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: mysql
    group: root
    mode: 0775
  with_items:
  - /var/lib/mysql
  - /setup
  - /var/lib/mysql

- name: Copy startup files
  copy:
    src: "{{ item }}"
    dest: /setup/
    owner: mysql
    group: root
    mode: 0664
  with_fileglob:
  - "./*" 

